### ISSUE TITLE
[Roadmap] 2019 - Q1

### ISSUE THREAD

**Issue by aghassemi** [ampproject/wg-components#2]
**UI Working Group**'s focus for Q1 of 2019 is launching new features and enhancements that improve the end-user experience on many existing AMP pages in the wild.

- [x] Input Masking https://github.com/ampproject/amphtml/issues/14745
- [ ] Infinite scroll for `amp-list` https://github.com/ampproject/amphtml/issues/14060
- [ ] Version 2 of `amp-carousel` with new features and enhancements https://github.com/ampproject/amphtml/issues/16509
- [x] Docking UI for videos https://github.com/ampproject/amphtml/issues/20235
- [ ] Default placeholders https://github.com/ampproject/amphtml/issues/9430 https://github.com/ampproject/amphtml/issues/20237
- [x] Auto lightboxing images (https://github.com/ampproject/amphtml/issues/20236
- [ ] Jank-free scrollbound animations using the new `animationWorklet` https://github.com/ampproject/amphtml/issues/13714
- [ ] Swipe to dismiss UX for image lightbox https://github.com/ampproject/amphtml/issues/19041
- [x] Configure `size` attribute for `amp-img` automatically https://github.com/ampproject/amphtml/issues/19513
- [x] Fully launch `amp-date-display` https://github.com/ampproject/amphtml/issues/20226
- [ ] Next version of AMP's end-to-end functional testing framework.

**Comment by nainar** [comment]
Updated the issue with master issues for video docking, auto lightbox images and default loaders.
